<?php
// Copyright 2014 Tristan van Bokkem

// Dutch Definitions for the Backup plugin.

$definitions["Add Create Database statement"] = "Voeg Create Database statement toe";
$definitions["Advanced Options"] = "Geavanceerde opties";
$definitions["Backup"] = "Backup";
$definitions["Backup & Download"] = "Backup & download";
$definitions["Backup Type"] = "Backup type";
$definitions["Character Set"] = "Karakterset";
$definitions["Check if the archive exists."] = "Controleer of het archiefbestand bestaat.";
$definitions["Check if the archive has the required permissions to be downloaded."] = "Controleer of het archiefbestand de juiste permissies heeft om te kunnen downloaden.";
$definitions["Check if the archive exists and if it has the required permissions to be removed."] = "Controleer of het archiefbestand bestaat en of het de juiste permissies heeft om te kunnen verwijderen.";
$definitions["Compression Type"] = "Compressie type";
$definitions["Create Backup"] = "Maak Backup";
$definitions["current charset"] = "huidig karakterset";
$definitions["Delete Backup"] = "Verwijder backup";
$definitions["Disable Auto Commit"] = "Schake Auto Commit uit";
$definitions["Disable Foreign Keys Check"] = "Schakel Foreign Keys Check uit";
$definitions["Disable Unique Keys Check"] = "Schake Unique Keys Check uit";
$definitions["Download Backup"] = "Download backup";
$definitions["Full"] = "Volledig";
$definitions["Maintenance"] = "Onderhoud";
$definitions["No Backups Available"] = "Geen backups beschikbaar";
$definitions["None"] = "Geen";
$definitions["Restore"] = "Herstel";
$definitions["Restore Backup"] = "Herstel backup";
$definitions["Structure Only"] = "Alleen structuur";
$definitions["Successfully created backup:"] = "Backup succesvol gemaakt:";
$definitions["Successfully deleted:"] = "Succesvol verwijderd:";
$definitions["Successfully restored database with archive:"] = "Database succesvol hersteld met archiefbestand:";
$definitions["Unable to delete:"] = "Verwijderen mislukt van:";
$definitions["Unable to download:"] = "Downloaden niet gelukt:";

$definitions["message.Backup.advanced"] = "<strong>Note:</strong> These options below are for expert users only and should not be changed if you don't know what you are doing.<br />The default settings will be fine for most users.";
$definitions["message.Backup.intro"] = "Here you can backup all your esoTalk related data. You may store the resulting archive in the uploads/backups folder or backup and download it directly.
Depending on your server configuration you may be able to compress the archive with GZIP compression.";
$definitions["message.Backup.restore"] = "This will perform a full restore of all esoTalk tables from a saved archive.<br />If your server supports it you may use a GZIP compressed
sql archive and it will automatically be decrompressed.<br /><br />
<strong>WARNING:</strong> This will overwrite any existing data. The restore may take a long time to process, please do <strong>not</strong>
move away from this page till it is complete. Backups are stored in the uploads/backups folder and are assumed to be generated by the esoTalk Backup Plugin functionality. Restoring backups
that were not created by this plugin will not work and might corrupt your database.";
